In [1]:
from utils_misc import pickle_load_or_create, pickle_save
from utils_cv2 import get_video_length, get_random_frame
import numpy as np
import pandas as pd
import sys

Defaulting to user installation because normal site-packages is not writeable


In [2]:
nr, frame = get_random_frame('../videos/20240201_atelier_004.mp4')
frame[1155][150]

array([203, 205, 207], dtype=uint8)

In [3]:
from DataRepository import DataRepository

Defaulting to user installation because normal site-packages is not writeable


In [4]:
repo = DataRepository()

connection established


In [5]:
repo.update_rectangle(5, 3, 0.4, 0.8, 0.1)

In [6]:
repo.query_framelabels(5)

Empty DataFrame
Columns: [videoID, frameNr, label, manual_insert, rect_center_x, rect_center_y, rect_size]
Index: []

In [7]:
frame[700:702,500:505] = [200,200,200]
frame[700:702,500:505]

array([[[200, 200, 200],
        [200, 200, 200],
        [200, 200, 200],
        [200, 200, 200],
        [200, 200, 200]],

       [[200, 200, 200],
        [200, 200, 200],
        [200, 200, 200],
        [200, 200, 200],
        [200, 200, 200]]], dtype=uint8)

In [8]:
frame.shape

(1920, 1080, 3)

In [9]:
get_video_length?

Signature: get_video_length(path)
Docstring: Returns the framelength of the video
File:      ~/code/judge/scripts/utils_cv2.py
Type:      function

In [10]:
from DataRepository import DataRepository


cls = DataRepository()


connection established


In [11]:
cls.uninserted_borders_to_framelabels()

[1 2 3 4 5 6 7 8 9]
doing video 1
doing video 2
doing video 3
doing video 4
doing video 5
doing video 6
doing video 7
doing video 8
doing video 9


In [3]:
cls.query_framelabels()



cls.get_path(2)

cls.get_randomized_borderlabels_and_batches_per_video(20)

videoID  batches_in_video  random_order  total_batches
0        4                19             1             19
1        3                23             2             42
2        2                38             3             80
3        1                24             4            104
4        6                16             5            120

In [4]:
cls.get_borderlabels_batch(videoID=3, batch_nr=22, batch_size=20)

frameNr  label
0      440      1
1      441      2
2      442      2
3      443      2

In [5]:
from utils_cv2 import get_frames, get_video_length

In [6]:
path = '../videos/20240201_atelier_003.mp4'

In [7]:
get_video_length(path)

1489

In [8]:
frames = get_frames('../videos/20240201_atelier_003.mp4', 1450, 1500, (150,150), rgb=True)
frames.shape

(51, 150, 150, 3)

In [9]:
frames[50][0], frames[22][0]

(array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0

In [10]:
from DataGeneratorBordersDB import DataGeneratorSkillBorders

gen = DataGeneratorSkillBorders(train=True, batch_size=20, dim=(128, 128), n_channels=3,
                 n_classes=5, shuffle=True, time_length=16)

2024-06-24 16:56:35.478732: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-06-24 16:56:35.517491: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-24 16:56:36.237032: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


connection established
DataGeneratorSkillBorders init done
on_epoch_end_called
   videoID  batches_in_video  random_order  total_batches
0        6                16             1             16
1        1                24             2             40
2        4                19             3             59
3        2                38             4             97
4        3                23             5            120


In [11]:
gen

In [12]:
gen.batch_order

videoID  batches_in_video  random_order  total_batches
0        6                16             1             16
1        1                24             2             40
2        4                19             3             59
3        2                38             4             97
4        3                23             5            120

In [13]:
%%time
for i in range(14,40):
    print(i)
    X, y = gen.__getitem__(i)
    print(X.shape, y.shape)

14
 getitem, batch_nr 14 train is: True
(1, 20, 128, 128, 3) (1, 20, 1)
15
 getitem, batch_nr 15 train is: True
fill_batch_size_dimension_called
(1, 20, 128, 128, 3) (1, 20, 1)
16
 getitem, batch_nr 16 train is: True
(1, 20, 128, 128, 3) (1, 20, 1)
17
 getitem, batch_nr 17 train is: True
(1, 20, 128, 128, 3) (1, 20, 1)
18
 getitem, batch_nr 18 train is: True
(1, 20, 128, 128, 3) (1, 20, 1)
19
 getitem, batch_nr 19 train is: True
(1, 20, 128, 128, 3) (1, 20, 1)
20
 getitem, batch_nr 20 train is: True
(1, 20, 128, 128, 3) (1, 20, 1)
21
 getitem, batch_nr 21 train is: True
(1, 20, 128, 128, 3) (1, 20, 1)
22
 getitem, batch_nr 22 train is: True
(1, 20, 128, 128, 3) (1, 20, 1)
23
 getitem, batch_nr 23 train is: True
(1, 20, 128, 128, 3) (1, 20, 1)
24
 getitem, batch_nr 24 train is: True
(1, 20, 128, 128, 3) (1, 20, 1)
25
 getitem, batch_nr 25 train is: True
(1, 20, 128, 128, 3) (1, 20, 1)
26
 getitem, batch_nr 26 train is: True
(1, 20, 128, 128, 3) (1, 20, 1)
27
 getitem, batch_nr 27 train 

In [14]:
X, y = gen.__getitem__(18)

 getitem, batch_nr 18 train is: True


In [15]:
X.shape

(1, 20, 128, 128, 3)

In [16]:
y.shape

(1, 20, 1)

In [17]:
y

array([[[3],
        [3],
        [3],
        [3],
        [3],
        [3],
        [3],
        [3],
        [3],
        [3],
        [3],
        [3],
        [3],
        [3],
        [3],
        [3],
        [0],
        [0],
        [0],
        [0]]])

In [18]:
cls.get_randomized_borderlabels_and_batches_per_video().iloc[-1]['total_batches']

149

In [19]:
cls.get_randomized_borderlabels_and_batches_per_video(batch_size=20, training=True)

videoID  batches_in_video  random_order  total_batches
0        3                23             1             23
1        6                16             2             39
2        2                38             3             77
3        1                24             4            101
4        4                19             5            120

In [20]:
len(gen)

len called len is: 120


120

In [21]:
len(gen)

len called len is: 120


120

In [22]:
cls.get_borderlabels_batch(videoID=1, batch_nr=23, batch_size=20)

frameNr  label
0       460      0
1       461      0
2       462      0
3       463      0
4       464      0
5       465      1
6       466      2
7       467      2
8       468      2
9       469      2
10      470      2
11      471      2
12      472      0
13      473      0
14      474      0
15      475      0
16      476      0
17      477      0
18      478      0
19      479      0

In [23]:
import numpy as np

In [24]:
y = np.where(y == 9, 3, y)
y = np.where(y == 8, 4, y)

In [25]:
y

array([[[3],
        [3],
        [3],
        [3],
        [3],
        [3],
        [3],
        [3],
        [3],
        [3],
        [3],
        [3],
        [3],
        [3],
        [3],
        [3],
        [0],
        [0],
        [0],
        [0]]])

In [26]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [27]:
# cls.add_border(8, 205, 215, 1)

In [28]:
cls.get_borders(8)

videoID  frame_start  frame_end  manual_insert
0        8          120        130              1
1        8          140        150              1
2        8          200        205              1
3        8          205        215              1

In [29]:
dfb = cls.get_borders(8)

In [30]:
cls.is_valid_border(8, 180, 190)

False

In [40]:
cls.get_border_overlap(8, 133, 200)

videoID  frame_start  frame_end  manual_insert
0        8          140        150              1

In [31]:
cls.get_border_overlap(8, 152, 540)

videoID  frame_start  frame_end  manual_insert
0        8          200        205              1
1        8          205        215              1

In [32]:
cls.get_border_overlap(8, 180, 190)

Empty DataFrame
Columns: [videoID, frame_start, frame_end, manual_insert]
Index: []

In [33]:
def get_overlap(dfb, start, end):
    return dfb[((start <= dfb['frame_start']) & (end > dfb['frame_start']) | (end >= dfb['frame_end']) & (start < dfb['frame_end']))]

In [34]:
get_overlap(dfb, 140, 150)

videoID  frame_start  frame_end  manual_insert
1        8          140        150              1

In [35]:
get_overlap(dfb, 140, 155)

videoID  frame_start  frame_end  manual_insert
1        8          140        150              1

In [36]:
get_overlap(dfb, 140, 145)

videoID  frame_start  frame_end  manual_insert
1        8          140        150              1

In [37]:
get_overlap(dfb, 135, 145)

videoID  frame_start  frame_end  manual_insert
1        8          140        150              1

In [38]:
get_overlap(dfb, 135, 155)

videoID  frame_start  frame_end  manual_insert
1        8          140        150              1

In [39]:
get_overlap(dfb, 150, 160)

Empty DataFrame
Columns: [videoID, frame_start, frame_end, manual_insert]
Index: []