In [1]:
from utils_misc import pickle_load_or_create, pickle_save

In [2]:
from DataRepository import DataRepository


cls = DataRepository()


Defaulting to user installation because normal site-packages is not writeable
Defaulting to user installation because normal site-packages is not writeable
connection established


In [3]:
cls.query_framelabels()



cls.get_path(2)

cls.get_randomized_borderlabels_and_batches_per_video(20)

videoID  batches_in_video  random_order  total_batches
0        2                38             1             38
1        4                19             2             57
2        5                20             3             77
3        1                24             4            101
4        6                16             5            117
5        3                23             6            140

In [4]:
cls.get_borderlabels_batch(videoID=3, batch_nr=22, batch_size=20)

frameNr  label
0      440      1
1      441      2
2      442      2
3      443      2

In [5]:
from utils_cv2 import get_frames, get_video_length

In [6]:
path = '../videos/20240201_atelier_003.mp4'

In [7]:
get_video_length(path)

1489

In [8]:
frames = get_frames('../videos/20240201_atelier_003.mp4', 1450, 1500, (150,150), rgb=True)
frames.shape

(51, 150, 150, 3)

In [9]:
frames[50][0], frames[22][0]

(array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0

In [10]:
from DataGeneratorBordersDB import DataGeneratorSkillBorders

gen = DataGeneratorSkillBorders(train=True, batch_size=20, dim=(128, 128), n_channels=3,
                 n_classes=5, shuffle=True, time_length=16)

2024-06-24 12:43:40.405912: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-06-24 12:43:40.452642: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-24 12:43:41.286627: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


connection established
DataGeneratorSkillBorders init done


In [11]:
gen

In [12]:
gen.batch_order

videoID  batches_in_video  random_order  total_batches
0        6                16             1             16
1        3                23             2             39
2        1                24             3             63
3        2                38             4            101
4        4                19             5            120
5        5                20             6            140

In [13]:
%%time
for i in range(14,40):
    print(i)
    X, y = gen.__getitem__(i)
    print(X.shape, y.shape)

14
 vidID 6 & vid_batch_nr 14
(1, 20, 128, 128, 3) (1, 20, 1)
15
 vidID 6 & vid_batch_nr 15
(1, 20, 128, 128, 3) (1, 20, 1)
16
 vidID 3 & vid_batch_nr 0
(1, 20, 128, 128, 3) (1, 20, 1)
17
 vidID 3 & vid_batch_nr 1
(1, 20, 128, 128, 3) (1, 20, 1)
18
 vidID 3 & vid_batch_nr 2
(1, 20, 128, 128, 3) (1, 20, 1)
19
 vidID 3 & vid_batch_nr 3
(1, 20, 128, 128, 3) (1, 20, 1)
20
 vidID 3 & vid_batch_nr 4
(1, 20, 128, 128, 3) (1, 20, 1)
21
 vidID 3 & vid_batch_nr 5
(1, 20, 128, 128, 3) (1, 20, 1)
22
 vidID 3 & vid_batch_nr 6
(1, 20, 128, 128, 3) (1, 20, 1)
23
 vidID 3 & vid_batch_nr 7
(1, 20, 128, 128, 3) (1, 20, 1)
24
 vidID 3 & vid_batch_nr 8
(1, 20, 128, 128, 3) (1, 20, 1)
25
 vidID 3 & vid_batch_nr 9
(1, 20, 128, 128, 3) (1, 20, 1)
26
 vidID 3 & vid_batch_nr 10
(1, 20, 128, 128, 3) (1, 20, 1)
27
 vidID 3 & vid_batch_nr 11
(1, 20, 128, 128, 3) (1, 20, 1)
28
 vidID 3 & vid_batch_nr 12
(1, 20, 128, 128, 3) (1, 20, 1)
29
 vidID 3 & vid_batch_nr 13
(1, 20, 128, 128, 3) (1, 20, 1)
30
 vidID 3 & vid_

In [14]:
X, y = gen.__getitem__(18)

 vidID 3 & vid_batch_nr 2


In [15]:
X.shape

(1, 20, 128, 128, 3)

In [16]:
y.shape

(1, 20, 1)

In [17]:
y

array([[[3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.]]])

In [18]:
cls.get_randomized_borderlabels_and_batches_per_video().iloc[-1]['total_batches']

174

In [19]:
cls.get_randomized_borderlabels_and_batches_per_video(batch_size=20, training=True)

videoID  batches_in_video  random_order  total_batches
0        6                16             1             16
1        4                19             2             35
2        2                38             3             73
3        3                23             4             96
4        1                24             5            120
5        5                20             6            140

In [20]:
len(gen)

len called len is: 140


140

In [21]:
len(gen)

140

In [22]:
cls.get_borderlabels_batch(videoID=1, batch_nr=23, batch_size=20)

frameNr  label
0       460      0
1       461      0
2       462      0
3       463      0
4       464      0
5       465      1
6       466      2
7       467      2
8       468      2
9       469      2
10      470      2
11      471      2
12      472      0
13      473      0
14      474      0
15      475      0
16      476      0
17      477      0
18      478      0
19      479      0

In [23]:
import numpy as np

In [24]:
y = np.where(y == 9, 3, y)
y = np.where(y == 8, 4, y)

In [25]:
y

array([[[3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.]]])

In [26]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])