In [34]:
from utils_misc import pickle_load_or_create, pickle_save
from utils_cv2 import get_video_length, get_random_frame
from DataRepository import DataRepository
from DataGeneratorFrames import DataGeneratorRectangles
import numpy as np
import pandas as pd
import sys
import os

In [35]:
repo = DataRepository()

connection established


In [36]:
repo.get_borders(222)

videoID  frame_start  frame_end  manual_insert  skip_in_learning
0       222          129        157              1                 0
1       222          157        185              1                 0
2       222          185        199              1                 0
3       222          199        212              1                 0
4       222          212        227              1                 0
..      ...          ...        ...            ...               ...
85      222         1844       1856              1                 0
86      222         1856       1868              1                 0
87      222         1868       1881              1                 0
88      222         1881       1902              1                 0
89      222          361        407              1                 0

[90 rows x 5 columns]

In [37]:
repo.query_framelabels(222)

videoID  frameNr  label  manual_insert  rect_center_x  rect_center_y  \
0         222        1      0              1       0.532031       0.593056   
1         222        2      0              1       0.532031       0.593056   
2         222        3      0              1       0.532031       0.593056   
3         222        4      0              1       0.532031       0.593056   
4         222        5      0              1       0.532031       0.593056   
...       ...      ...    ...            ...            ...            ...   
1968      222     1969      0              1       0.558594       0.611111   
1969      222     1970      0              1       0.558594       0.611111   
1970      222     1971      0              1       0.558594       0.611111   
1971      222     1972      0              1       0.558594       0.611111   
1972      222     1973      0              1       0.558594       0.611111   

      rect_size  
0      0.536499  
1      0.536499  
2      0.536499  
3      0.536499  
4      0.536499  
...         ...  
1968   0.685151  
1969   0.685151  
1970   0.685151  
1971   0.685151  
1972   0.685151  

[1973 rows x 7 columns]

In [38]:
root = '/media/miked/Elements/Judge/FINISHED-DB-READY/'

In [39]:
repo.get_ageID('junsen')

5

In [40]:
gen = DataGeneratorRectangles(batch_size=8, train=True, rootfolder=root)

connection established
DataGeneratorSkillBorders init done
on_epoch_end_called


In [41]:
gen.batch_order.sort_values(['videoID','batch_nr_video'])


videoID  batch_nr_video  frame_start  frame_end  frames  batch_id
376         1               0            1          8       8       376
3580        1               1            9         16       8      3580
755         1               2           17         24       8       755
960         1               3           25         32       8       960
2638        1               4           33         40       8      2638
...       ...             ...          ...        ...     ...       ...
2189      245             247         1977       1984       8      2189
3627      245             248         1985       1992       8      3627
3459      245             249         1993       2000       8      3459
2431      245             250         2001       2008       8      2431
1753      245             251         2009       2009       1      1753

[4022 rows x 6 columns]

In [42]:
gen.batch_order[(gen.batch_order['frames'] < 8)]


videoID  batch_nr_video  frame_start  frame_end  frames  batch_id
145        30             101          809        814       6       145
440         3             186         1489       1489       1       440
616        11             233         1865       1868       4       616
634         1              92          737        737       1       634
800       110             119          957        960       4       800
833        75              92          740        744       5       833
1150      110             233         1865       1870       6      1150
1223       52               0            1          3       3      1223
1382        7             167         1337       1340       4      1382
1604      120             259         2073       2073       1      1604
1753      245             251         2009       2009       1      1753
1893      110             118          945        947       3      1893
2154        4             260         2081       2081       1      2154
2300        2             179         1433       1435       3      2300
2625        2             178         1430       1432       3      2625
2739      100             250         2001       2007       7      2739
2859       30             101          816        816       1      2859
3056      100              48          391        392       2      3056
3355       52             211         1690       1696       7      3355
3432       75              87          697        703       7      3432
3435       30             249         1993       1994       2      3435
3525      100              48          385        387       3      3525
3595        2             104          833        833       1      3595
3791       52             254         2033       2034       2      3791
3830       16             248         1985       1989       5      3830
3937       52               1           14         16       3      3937
3983       52             210         1681       1687       7      3983
4000        5             317         2537       2538       2      4000

In [43]:
gen.batch_order[(gen.batch_order['frames'] < 8) & (gen.batch_order['videoID'] == 52)]


videoID  batch_nr_video  frame_start  frame_end  frames  batch_id
1223       52               0            1          3       3      1223
3355       52             211         1690       1696       7      3355
3791       52             254         2033       2034       2      3791
3937       52               1           14         16       3      3937
3983       52             210         1681       1687       7      3983

In [44]:
repo.get_rectangles_from_batch(100, 380,400)

videoID  frameNr  label  manual_insert  rect_center_x  rect_center_y  \
0       100      380      2              1       0.334375       0.605556   
1       100      381      2              1       0.334375       0.605556   
2       100      382      2              1       0.334375       0.605556   
3       100      383      2              1       0.316146       0.622222   
4       100      384      2              1       0.316146       0.622222   
5       100      385      2              1       0.316146       0.622222   
6       100      386      1              1       0.316146       0.622222   
7       100      387      1              1       0.316146       0.622222   
8       100      391      2              1       0.309896       0.624074   
9       100      392      2              1       0.309896       0.624074   
10      100      393      2              1       0.309896       0.624074   
11      100      394      2              1       0.309896       0.624074   
12      100      395      2              1       0.309896       0.624074   
13      100      396      2              1       0.309896       0.624074   
14      100      397      2              1       0.309896       0.624074   
15      100      398      2              1       0.309896       0.624074   
16      100      399      2              1       0.314583       0.618519   
17      100      400      2              1       0.314583       0.618519   

    rect_size  
0    0.641185  
1    0.680233  
2    0.680233  
3    0.700640  
4    0.700640  
5    0.721660  
6    0.721660  
7    0.788577  
8    0.836601  
9    0.836601  
10   0.836601  
11   0.836601  
12   0.887550  
13   0.887550  
14   0.887550  
15   0.887550  
16   0.941602  
17   0.941602

In [45]:
X, y = gen.__getitem__(2630)

 __getitem__(2630)


In [46]:
X.shape

(8, 128, 128, 3)

In [47]:
y.shape

(8, 3)

In [48]:
y

array([[0.557031, 0.6     , 0.541352],
       [0.557031, 0.6     , 0.541352],
       [0.557031, 0.6     , 0.541352],
       [0.557031, 0.6     , 0.541352],
       [0.557031, 0.6     , 0.541352],
       [0.557031, 0.6     , 0.541352],
       [0.557031, 0.6     , 0.541352],
       [0.557031, 0.6     , 0.541352]])

In [49]:
repo.get_rectangles_from_batch(videoID=52, frame_start=14, frame_end=16)

videoID  frameNr  label  manual_insert  rect_center_x  rect_center_y  \
0       52       14      0              1       0.521354       0.586111   
1       52       15      0              1       0.521354       0.586111   
2       52       16      0              1       0.521354       0.586111   

   rect_size  
0       0.97  
1       0.97  
2       0.97

In [50]:
for i in gen.batch_order[(gen.batch_order['frames'] < 8)].index.values:
    X, y = gen.__getitem__(i)
    print(X.shape, y.shape)

 __getitem__(145)
(6, 128, 128, 3) (6, 3)
 __getitem__(440)
(1, 128, 128, 3) (1, 3)
 __getitem__(616)
(4, 128, 128, 3) (4, 3)
 __getitem__(634)
(1, 128, 128, 3) (1, 3)
 __getitem__(800)
(4, 128, 128, 3) (4, 3)
 __getitem__(833)
(5, 128, 128, 3) (5, 3)
 __getitem__(1150)
(6, 128, 128, 3) (6, 3)
 __getitem__(1223)
(3, 128, 128, 3) (3, 3)
 __getitem__(1382)
(4, 128, 128, 3) (4, 3)
 __getitem__(1604)
(1, 128, 128, 3) (1, 3)
 __getitem__(1753)
(1, 128, 128, 3) (1, 3)
 __getitem__(1893)
(3, 128, 128, 3) (3, 3)
 __getitem__(2154)
(1, 128, 128, 3) (1, 3)
 __getitem__(2300)
(3, 128, 128, 3) (3, 3)
 __getitem__(2625)
(3, 128, 128, 3) (3, 3)
 __getitem__(2739)
(7, 128, 128, 3) (7, 3)
 __getitem__(2859)
(1, 128, 128, 3) (1, 3)
 __getitem__(3056)
(2, 128, 128, 3) (2, 3)
 __getitem__(3355)
(7, 128, 128, 3) (7, 3)
 __getitem__(3432)
(7, 128, 128, 3) (7, 3)
 __getitem__(3435)
(2, 128, 128, 3) (2, 3)
 __getitem__(3525)
(3, 128, 128, 3) (3, 3)
 __getitem__(3595)
(1, 128, 128, 3) (1, 3)
 __getitem__(3791

In [94]:
### Predicting frames

In [95]:
from utils_cv2 import get_frames

In [132]:
vidid=8
frame_start=120
frame_end=125
path = root + repo.get_path(videoID=vidid)
path

'/media/miked/Elements/Judge/FINISHED-DB-READY/free-vids/SR1/mike/mike-20240209-atelier-008.mp4'

In [133]:
X = get_frames(path, frame_start, frame_end, dim=(256,256))
X.shape

(6, 256, 256, 3)

In [134]:
model = pickle_load_or_create('../models/frames_skillborder_CNN_model_96pixels_history', lambda: None, True).model
print(model)

<Sequential name=sequential, built=True>


In [135]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 254, 254, 24)   │           672 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 127, 127, 24)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 127, 127, 24)   │            96 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 125, 125, 32)   │         6,944 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 62, 62, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 62, 62, 32)     │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 60, 60, 48)     │        13,872 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 30, 30, 48)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_2           │ (None, 30, 30, 48)     │           192 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 43200)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 64)             │     2,764,864 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 3)              │           195 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 8,360,475 (31.89 MB)

 Trainable params: 2,786,755 (10.63 MB)

 Non-trainable params: 208 (832.00 B)

 Optimizer params: 5,573,512 (21.26 MB)

In [136]:
X

array([[[[0.3372549 , 0.36078431, 0.38039216],
         [0.3372549 , 0.35686275, 0.38039216],
         [0.34509804, 0.36078431, 0.39607843],
         ...,
         [0.3372549 , 0.35686275, 0.38039216],
         [0.32941176, 0.34901961, 0.37254902],
         [0.31764706, 0.34117647, 0.37647059]],

        [[0.34117647, 0.36470588, 0.38039216],
         [0.34509804, 0.36862745, 0.38431373],
         [0.34509804, 0.36470588, 0.38823529],
         ...,
         [0.3372549 , 0.35686275, 0.38039216],
         [0.31764706, 0.3372549 , 0.36078431],
         [0.3254902 , 0.34901961, 0.38431373]],

        [[0.36078431, 0.38039216, 0.40392157],
         [0.34901961, 0.37647059, 0.4       ],
         [0.3372549 , 0.36470588, 0.38823529],
         ...,
         [0.33333333, 0.36470588, 0.38039216],
         [0.32941176, 0.35686275, 0.38039216],
         [0.33333333, 0.36078431, 0.38431373]],

        ...,

        [[0.64313725, 0.63137255, 0.62745098],
         [0.64705882, 0.63529412, 0.63137255]

In [137]:
np.set_printoptions(suppress=True)
np.round(model.predict(X), 2)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 282ms/step


array([[ 28.84, -59.53, 175.36],
       [ 33.42, -70.02, 185.41],
       [ 29.96, -64.18, 180.62],
       [ 27.62, -58.11, 176.79],
       [ 25.89, -55.7 , 176.54],
       [ 27.05, -55.6 , 175.84]], dtype=float32)

In [138]:
X

array([[[[0.3372549 , 0.36078431, 0.38039216],
         [0.3372549 , 0.35686275, 0.38039216],
         [0.34509804, 0.36078431, 0.39607843],
         ...,
         [0.3372549 , 0.35686275, 0.38039216],
         [0.32941176, 0.34901961, 0.37254902],
         [0.31764706, 0.34117647, 0.37647059]],

        [[0.34117647, 0.36470588, 0.38039216],
         [0.34509804, 0.36862745, 0.38431373],
         [0.34509804, 0.36470588, 0.38823529],
         ...,
         [0.3372549 , 0.35686275, 0.38039216],
         [0.31764706, 0.3372549 , 0.36078431],
         [0.3254902 , 0.34901961, 0.38431373]],

        [[0.36078431, 0.38039216, 0.40392157],
         [0.34901961, 0.37647059, 0.4       ],
         [0.3372549 , 0.36470588, 0.38823529],
         ...,
         [0.33333333, 0.36470588, 0.38039216],
         [0.32941176, 0.35686275, 0.38039216],
         [0.33333333, 0.36078431, 0.38431373]],

        ...,

        [[0.64313725, 0.63137255, 0.62745098],
         [0.64705882, 0.63529412, 0.63137255]

In [139]:
repo.get_rectangles_from_batch(vidid, frame_start, frame_end)

videoID  frameNr  label  manual_insert  rect_center_x  rect_center_y  \
0        8      120      0              1       0.255556       0.554167   
1        8      121      1              1       0.255556       0.554167   
2        8      122      1              1       0.255556       0.554167   
3        8      123      2              1       0.255556       0.554167   
4        8      124      2              1       0.255556       0.554167   
5        8      125      2              1       0.255556       0.554167   

   rect_size  
0     1.0888  
1     1.0888  
2     1.0888  
3     1.0888  
4     1.0888  
5     1.0888

In [140]:
np.round?

Signature:       np.round(a, decimals=0, out=None)
Call signature:  np.round(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function round at 0x7742a41b0430>
File:            ~/.local/lib/python3.10/site-packages/numpy/core/fromnumeric.py
Docstring:      
Evenly round to the given number of decimals.

Parameters
----------
a : array_like
    Input data.
decimals : int, optional
    Number of decimal places to round to (default: 0).  If
    decimals is negative, it specifies the number of positions to
    the left of the decimal point.
out : ndarray, optional
    Alternative output array in which to place the result. It must have
    the same shape as the expected output, but the type of the output
    values will be cast if necessary. See :ref:`ufuncs-output-type` for more
    details.

Returns
-------
rounded_array : ndarray
    An array of the same type as `a`, containing the rounded values.
    Unless `out` was specified, a new array is created.  A refe